name: Release

on:
  release:
    types:
      - created

jobs:
  release:
    name: "Publish release"
    runs-on: ubuntu-latest

    steps:
      - uses: "actions/checkout@v3"
      - uses: "actions/setup-python@v1"
        with:
          python-version: 3.8
      - name: "Install dependencies"
        run: "pip install -r requirements/dev-requirements.txt"
      - name: "Publish to PyPI"
        run: "./scripts/release.sh"
        env:
          TWINE_USERNAME: ${{ secrets.PYPI_USERNAME }}
          TWINE_PASSWORD: ${{ secrets.PYPI_PASSWORD }}
